### ISSUE TITLE
Connection error 

### ISSUE THREAD

**Issue by Ox7599** [zamanzadeh/ts-anomaly-benchmark#1]
you may be need to delete `hfwnet`
![image](https://github.com/user-attachments/assets/73100df3-854d-4d78-84f3-85fa6fad0cdd)

![image](https://github.com/user-attachments/assets/12c2d38a-65b7-4c72-966b-fa56b3adc35f)

**Comment by zamanzadeh** [comment]
Thanks for letting me know! Corrected
